<?php
/**
 * @file
 * Code for the PSC Positions feature.
 */

include_once 'psc_positions.features.inc';

/**
 * Custom form for filtering on the serve page
 */
function psc_positions_serve_filter($form, &$form_state, $path = 'serve') {
  $form = array();
  
  $form['#attributes'] = array(
    'class' => array(
      'uniform',
      'uniform-compact',
      'form-serve-ministry',
    ),
  );
  
  $form['i2i_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => '',
    '#title_display' => 'invisible',
    '#tree' => FALSE,
    'fields_wrapper' => array(
      '#type' => 'container',
      '#attributes' => array(
        'class' => array(
          'fields-wrapper',
          'group',
        ),
      ),
      '#prefix' => '<legend class="brand-alpha-black brand-standout">' . t('Find an Area to Serve') . '</legend>',
      'inner_group' => array(
        '#type' => 'container',
        '#attributes' => array(
          'class' => array(
            'inner',
            'group',
          ),
        ),
        'field_focus' => array(
          '#type' => 'container',
          '#attributes' => array(
            'class' => array (
              'field-focus',
            ),
          ),
          'field_ministry' => array(
            '#type' => 'container',
            '#attributes' => array(
              'class' => array(
                'field',
                'field-select',
              ),
              'id' => 'form-serve-ministry',
            ),
            'serve_ministry' => array(
              '#type' => 'select',
              '#title' => t('Select a Ministry'),
              '#options' => array('' => t('Select a Ministry')) + psc_positions_get_ministry_options(),
            ),
          ),
        ),
        'skills_wrapper' => array(
          '#type' => 'container',
          '#attributes' => array(
            'class' => array(
              'well',
            ),
          ),
          'skills_header' => array(
            '#markup' => t('I have skills or interest in'),
            '#prefix' => '<h5 class="well-title brand-alpha-black brand-standout">',
            '#suffix' => '</h5>',
          ),
          'col_4_wrapper' => array(
            '#type' => 'container',
            '#attributes' => array(
              'class' => array(
                'group',
                'col-wrapper-4',
              ),
            ),
            'skills' => array(
              '#tree' => TRUE,
            ),
          ),
        ),
        'form_actions' => array(
          '#type' => 'container',
          '#attributes' => array(
            'class' => array(
              'form-actions',
            ),
          ),
          'submit' => array(
            '#type' => 'submit',
            '#value' => t('Find Area to Serve'),
          ),
        ),
      ),
    ),
  );
  
  $form['path'] = array(
    '#type' => 'hidden',
    '#value' => $path,
  );
  
  $form['#submit'][] = 'psc_positions_serve_filter_submit';
  
  $skills_options = psc_positions_get_skills_options();
  $counter = 1;
  
  foreach ($skills_options as $tid => $name) {
    $form['i2i_fieldset']['fields_wrapper']['inner_group']['skills_wrapper']['col_4_wrapper']['skills'][$tid] = array(
      '#type' => 'checkbox',
      '#title' => t('@name', array('@name' => $name)),
      '#return_value' => $tid,
      '#prefix' => '<div class="col col-' . $counter . '">',
      '#suffix' => '</div>',
    );
    
    if ($counter == 4) {
      $counter = 1;
    } else {
      $counter++;
    }
  }
  
  return $form;
}

/**
 * Submit handler for the positions filter form
 */
function psc_positions_serve_filter_submit(&$form, &$form_state) {
  $ministry_nid = !empty($form_state['values']['serve_ministry']) ? $form_state['values']['serve_ministry'] : 'all';
  $skills = array();
  
  if (!empty($form_state['values']['skills'])) {
    foreach ($form_state['values']['skills'] as $tid => $val) {
      if (!empty($val)) {
        $skills[] = $tid;
      }
    }
  }
  
  $form_state['redirect'] = $form_state['values']['path'] . '/' . $ministry_nid . '/' . implode('+', $skills);
}

/**
 * Get all the ministry options to choose from
 */
function psc_positions_get_ministry_options() {
  $ministry_node_type = variable_get('psc_positions_ministry_node_type', 'ministry_detail');
  
  $sql =
    'SELECT ' .
      '`nid`, ' .
      '`title` ' .
    'FROM {node} ' .
    'WHERE `type` = :node_type ' .
      'AND `status` = :status ' .
    'ORDER BY `status` DESC, `type`, `title` ASC;';
  return _psc_positions_options_db_query_handler($sql, 'nid', 'title', array(':node_type' => $ministry_node_type, ':status' => 1));
}

/**
 * Get all the volunter skills options to choose from
 */
function psc_positions_get_skills_options() {
  $skills_vid = variable_get('psc_positions_skills_vid', 2);
  
  $sql =
    'SELECT ' . 
      '`tid`, ' .
      '`name` ' .
    'FROM {taxonomy_term_data} ' .
    'WHERE `vid` = :vid ' .
    'ORDER BY `vid`, `name`;';
  return _psc_positions_options_db_query_handler($sql, 'tid', 'name', array(':vid' => $skills_vid));
}

/**
 * Database query result options builder
 */
function _psc_positions_options_db_query_handler($sql, $key_col, $val_col, $args = array()) {
  $options = array();
  $result = db_query($sql, $args);
  
  foreach ($result as $row) {
    $options[$row->{$key_col}] = $row->{$val_col};
  }
  
  return $options;
}
